### PR TITLE
feat: added support for autogenerated chapters

### LINKED ISSUE #88: deps: switch to some other youtube lib to download the youtube videos
The Pytube lib is no longer being maintained and thus the download feature no longer works. We need to immediately switch from pytube to some other lib, maybe yt-dlp. This issue has been listed on the pytube repo for a 3 days now with no response from the maintainers. 
image

### PR DESCRIPTION
**Pull request by masterchief164**
This PR fixes #88 and #74.

### CODE REVIEW

**Comment by adamjonas** [comment]
Failing tests similar to the CI:

```
FAILED test/test_cli.py::test_download_video_file - AssertionError: assert (True and False)
FAILED test/test_cli.py::test_chapter_creation - TypeError: read_description() takes 0 positional arguments but 1 was given
FAILED test/test_cli.py::test_split_video - TypeError: read_description() takes 0 positional arguments but 1 was given
FAILED test/test_video.py::test_video_with_chapters - FileNotFoundError: [Errno 2] No such file or directory: 'test/testAssets/test_video.chapters'
```

**Comment by adamjonas** [comment]
can you take care of this extra space in here as well? https://github.com/adamjonas/bitcointranscripts/pull/92/files#r1144104976

**Comment by adamjonas** [comment]
this is a weird one. Maybe we skip if we get this header? https://github.com/adamjonas/bitcointranscripts/pull/98/files#r1144118042

**Comment by adamjonas** [comment]
These chapter headers are magical though. This is a great addition.

**Comment by masterchief164** [comment]
> this is a weird one. Maybe we skip if we get an empty header? https://github.com/adamjonas/bitcointranscripts/pull/98/files#r1144118042 https://github.com/adamjonas/bitcointranscripts/pull/95/files#r1144118750 https://github.com/adamjonas/bitcointranscripts/pull/94/files#r1144119029

I've fixed the issues please check again.

**Comment by adamjonas** [comment]
ea20f3a79d7f5c0faa44fd6c82b20333fb1cd8f7 no longer works:

```
( issue_88 )  > tstbtc 'https://www.youtube.com/watch?v=s9KMRWkcwtE' tabconf/2022 -C
Transcribing video: https://www.youtube.com/watch?v=s9KMRWkcwtE
URL: https://www.youtube.com/watch?v=s9KMRWkcwtE
Downloading video... Please wait.
[youtube] Extracting URL: https://www.youtube.com/watch?v=s9KMRWkcwtE
[youtube] s9KMRWkcwtE: Downloading webpage
[youtube] s9KMRWkcwtE: Downloading android player API JSON
[info] s9KMRWkcwtE: Downloading 1 format(s): 18
[info] Writing video metadata as JSON to: tmp/videoFile.info.json
[download] Destination: tmp/videoFile.mp4
[download] 100% of   92.77MiB in 00:00:47 at 1.94MiB/s


Error processing video
'chapters'
Cleaning up...
```

Without the flag works fine:

```
( issue_88 )  > tstbtc 'https://www.youtube.com/watch?v=s9KMRWkcwtE' tabconf/2022
Transcribing video: https://www.youtube.com/watch?v=s9KMRWkcwtE
URL: https://www.youtube.com/watch?v=s9KMRWkcwtE
Downloading video... Please wait.
[youtube] Extracting URL: https://www.youtube.com/watch?v=s9KMRWkcwtE
[youtube] s9KMRWkcwtE: Downloading webpage
[youtube] s9KMRWkcwtE: Downloading android player API JSON
[info] s9KMRWkcwtE: Downloading 1 format(s): 18
[info] Writing video metadata as JSON to: tmp/videoFile.info.json
[download] Destination: tmp/videoFile.mp4
[download] 100% of   92.77MiB in 00:01:06 at 1.39MiB/s


Converting video to mp3... Please wait.
/Users/jonas/chaincode/yt2btc/tmp/Lightning is Broken AF (But We Can Fix It) - Matt Corallo.mp3
MoviePy - Writing audio in /Users/jonas/chaincode/yt2btc/tmp/Lightning is Broken AF (But We Can Fix It) - Matt Corallo.mp3
MoviePy - Done.
Converted video to mp3
Transcribing audio to text...
Removed video and audio files
writing .md file
wrote .md file
Transcription complete
Cleaning up...
```

**Pull request merged**
